# Generated by Django 5.1.1 on 2024-10-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
