# Generated by Django 5.1.1 on 2024-10-30 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_doctor_department_doctor_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctors', models.ManyToManyField(to='doctor.doctor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
