export const APP_ROUTER = {
    HOME: '/home',
    ABOUT: '/about',
    SERVICE: '/service',
    DOCTOR: '/doctor',
    CONTACT: '/contact',
    LOGIN: '/login',
    BOOKAPOINT: '/bookappointment',
    DETAILAPOINT: '/detailappointment',
    BLOG: '/blogspage',
    ADDASHBOARD: '/admin/dashboard',
    CALENDAR: '/admin/calendar',
    DOCTOR: '/admin/doctor',
    DEPARTMENT: '/admin/department',
    PATIENT: '/admin/patientlist',
    PAYMENT: '/admin/paymentpage',
    BLOG: '/admin/blogspage',
};