export const APP_ROUTER = {
    HOME: '/home',
    SERVICE: '/service',
    SINGLEDOCTOR: '/singledoctor',
    CONTACT: '/contact',
    LOGIN: '/login',
    BOOKAPOINT: '/bookappointment',
    PROFILE: '/profile',
    NOTIFICATIONS: '/notifications',
    SCHEDULE: '/schedule',
    DETAILAPOINT: '/detailappointment',
    BLOG: '/blogspage',
    DOCTORS: '/doctor',
    ADDASHBOARD: '/admin/dashboard',
    CALENDAR: '/admin/calendar',
    DOCTOR: '/admin/doctor',
    DEPARTMENT: '/admin/department',
    PATIENT: '/admin/patientlist',
    PAYMENT: '/admin/paymentpage',
    MEDICALRECORD: '/medical-record',
};